spring:
  profiles:
    active: dev
---
server:
  port: 6001
spring:
  profiles: dev
  application:
    name: microservice-eureka-6001

eureka:
  instance:
    hostname: eureka6001.com
  client:
    registerWithEureka: false
	fetchRegistry: false
	serviceUrl:
      defaultZone: http://eureka6002.com:6002/eureka/
  server:
    enable-self-preservation: false

---
server:
  port: 6001
spring:
  profiles: prod
  application:
    name: microservice-eureka-6001

eureka:
  instance:
    hostname: eureka6001.com
  client:
    registerWithEureka: false
	fetchRegister: false
	serviceUrl:
	  defaultZone: http://eureka6002.com:6002/eureka/
  server:
    enable-self-preservation: true